# Generated by Django 3.1 on 2020-08-04 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudante',
            options={'ordering': ['nome'], 'verbose_name': 'Estudante', 'verbose_name_plural': 'Estudantes'},
        ),
        migrations.RenameField(
            model_name='estudante',
            old_name='course',
            new_name='curso',
        ),
        migrations.RenameField(
            model_name='estudante',
            old_name='name',
            new_name='nome',
        ),
    ]
